# Базовый образ для сборки приложения
FROM node:20

# Создаем и устанавливаем директорию приложения
WORKDIR /app

# Копируем зависимости приложения (package.json и package-lock.json)
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем остальные файлы приложения
COPY . .

EXPOSE 3000

CMD [ "npm", "run", "start:dev" ]
