name: CI-Pipeline-Deployment

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Executing remote SSH
      uses: appleboy/ssh-action@master
      with:
        port: 22
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          cd app
          git pull
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          chmod +x deploy.sh
          ./deploy.sh

